### ISSUE TITLE
error-500 无法创建实体

### ISSUE THREAD

**Issue by bobandyou** [getrebuild/rebuild#107]
## 版本号
TODO
1.7.0
## 什么问题
TODO
MetadataException : entity [ undefined ] dose not exists
## 如何复现此问题
TODO
创建实体时
## 系统环境（操作系统/浏览器）
TODO
rebuild 安装在win10
浏览器 maxthon
mysql 5.7.23 安装在docker上

**Comment by devezhao** [comment]
确认 MySQL 用户有建表权限

**Comment by bobandyou** [comment]
rebuild用户和root用户都试过，安装rebuild成功了，说明建表权限没有问题。
创建新实体时出现以上问题。
H2数据库没有这个问题。
本机运行mysql也试过，问题依旧。

**Comment by bobandyou** [comment]
你这个平台很精妙啊，我看那些开源评分较高的平台很多方面不如rebuild构思精巧简练。

**Comment by bobandyou** [comment]
[ERROR 13:25:46,253] <http-nio-18080-exec-5> web.RequestWatchHandler#afterCompletion:128 -
++ EXECUTE REQUEST ERROR(s) TRACE +++++++++++++++++++++++++++++++++++++++++++++
User      : 001-0000000000000001
Handler   : /admin/entity/undefined/base [ public org.springframework.web.servlet.ModelAndView com.rebuild.web.admin.entityhub.MetaEntityControll.pageEntityBase(java.lang.String) throws java.io.IOException ]
IP        : 127.0.0.1
Referer   : http://127.0.0.1:18080/admin/p/entityhub/entity-new
UserAgent : Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36 Maxthon/5.0
Cause     : cn.devezhao.persist4j.metadata.MetadataException
Message   : entity [ undefined ] dose not exists
cn.devezhao.persist4j.metadata.MetadataException: entity [ undefined ] dose not exists
        at cn.devezhao.persist4j.metadata.impl.ConfigurationMetadataFactory.getEntityNoLock(ConfigurationMetadataFactory.java:80)
        at cn.devezhao.persist4j.metadata.impl.ConfigurationMetadataFactory.getEntity(ConfigurationMetadataFactory.java:74)
        at com.rebuild.server.metadata.MetadataHelper.getEntity(MetadataHelper.java:109)
        at com.rebuild.server.metadata.entity.EasyMeta.valueOf(EasyMeta.java:337)
        at com.rebuild.web.admin.entityhub.MetaEntityControll.setEntityBase(MetaEntityControll.java:238)
        at com.rebuild.web.admin.entityhub.MetaEntityControll.pageEntityBase(MetaEntityControll.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by devezhao** [comment]
麻烦上传一个完整日志文件上来。如果你用标准安装包，那么他位于安装目录内的 `/temp/logs/rebuild`

**Comment by bobandyou** [comment]
刚才测试了一下，1.6版本没有问题。

**Comment by bobandyou** [comment]
上传rebuild log

**Comment by bobandyou** [comment]
[rebuild.txt](https://github.com/getrebuild/rebuild/files/3992242/rebuild.txt)

**Comment by bobandyou** [comment]
日子文件，我加了txt后缀名。

**Comment by bobandyou** [comment]
建议你在干净的系统，没有安装过rebuild的情况下测试。
在不同的数据库版安装也有点问题。

**Comment by devezhao** [comment]
> 建议你在干净的系统，没有安装过rebuild的情况下测试。
> 在不同的数据库版安装也有点问题。

每个 PR 的自动化 CI 会在全新的环境下执行所有单元测试。
你这个问题的原因在这里
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'CREATED_ON'
```
MySQL 5.7 开始默认不允许日期默认值为 `0000-00-00`，一个简单的办法是设置 MySQL 使其允许。方式如下：
1. 查询当前模式
```
select @@sql_mode
```
2. 将查询结果中的 `NO_ZERO_IN_DATE` `NO_ZERO_DATE` 去除备用
3. 打开 MySLQ 配置文件，在 `[mysqld]` 这一行下面加入（如果已经有 `sql_mode` 可以直接按步骤2去除）
```
sql_mode=步骤2的字符串
```
4. 重启 MySQL 即可

当然，我们会修复这个问题，谢谢你的反馈。
