### ISSUE TITLE
经常报莫名奇妙的错误，貌似是cookie操作问题  ServletUtils.readCookie  ServletUtils.readCookie 没有源码

### ISSUE THREAD

**Issue by allenlei2010** [getrebuild/rebuild#109]
## 版本号
1.7.0

## 什么问题

严重: Error processing request
java.lang.IllegalArgumentException: Control character in cookie value or attribute.
	at org.apache.tomcat.util.http.LegacyCookieProcessor.isV0Separator(LegacyCookieProcessor.java:729)
	at org.apache.tomcat.util.http.LegacyCookieProcessor.processCookieHeader(LegacyCookieProcessor.java:526)
	at org.apache.tomcat.util.http.LegacyCookieProcessor.parseCookieHeader(LegacyCookieProcessor.java:256)
	at org.apache.catalina.connector.Request.parseCookies(Request.java:3077)
	at org.apache.catalina.connector.Request.getServerCookies(Request.java:2093)
	at org.apache.catalina.connector.CoyoteAdapter.parseSessionCookiesId(CoyoteAdapter.java:1218)
	at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:925)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:497)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

## 如何复现此问题
TODO

## 系统环境（操作系统/浏览器）
TODO

**Comment by getrebuild** [comment]
看错误应该是 Cookie 中有特殊字符导致，提供下 Tomcat 版本号和操作系统以及语言环境。
另 ServletUtils 也有源码，托管在 JitPick https://jitpack.io/#devezhao/commons

**Comment by allenlei2010** [comment]
tomcat版本：apache-tomcat-8.0.53
os：win10 ，默认系统编码gbk

**Comment by allenlei2010** [comment]
还是不行，使用了最新的commons包，仍然是报同样的错误
[WARN 14:32:47,880] web.RequestWatchHandler#logProgressTime:146 - Method handle time 745 ms. Request URL [ /rebuild/user/login ] from [ http://localhost:8080/rebuild/ ]
十二月 23, 2019 2:32:50 下午 org.apache.coyote.http11.AbstractHttp11Processor process
严重: Error processing request
java.lang.IllegalArgumentException: Control character in cookie value or attribute.
at org.apache.tomcat.util.http.LegacyCookieProcessor.isV0Separator(LegacyCookieProcessor.java:729)
at org.apache.tomcat.util.http.LegacyCookieProcessor.processCookieHeader(LegacyCookieProcessor.java:526)
at org.apache.tomcat.util.http.LegacyCookieProcessor.parseCookieHeader(LegacyCookieProcessor.java:256)
at org.apache.catalina.connector.Request.parseCookies(Request.java:3077)
at org.apache.catalina.connector.Request.getServerCookies(Request.java:2093)
at org.apache.catalina.connector.CoyoteAdapter.parseSessionCookiesId(CoyoteAdapter.java:1218)
at org.apache.catalina.connector.CoyoteAdapter.postParseRequest(CoyoteAdapter.java:925)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:497)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

不过用firefox没问题，使用360浏览器报这个错，是不是跟浏览器有关啊？

**Comment by devezhao** [comment]
使用 tomcat8.0 + 360 浮现不出来，先关掉了
