### ISSUE TITLE
boot

### ISSUE THREAD

**Issue by aertaa** [getrebuild/rebuild#186]
### 版本
1.10.0

### 什么问题 
启动时 tomcat 控制台报错如下：
[INFO  20:39:33,439] <http-nio-80-exec-13> setup.UpgradeDatabase#upgrade:55 - Upgrade SQL(#24) >
create table if not exists `smsend_log` (
  `SEND_ID`            char(20) not null,
  `TO`                 varchar(100) not null comment '收件人',
  `CONTENT`            text(21845) not null comment '发送内容',
  `SEND_TIME`          timestamp not null default current_timestamp comment '发送时间',
  `SEND_RESULT`        varchar(200) comment '发送结果(OK:xxx|ERR:xxx)',
  primary key  (`SEND_ID`),
  index IX0_smsend_log (`SEND_TIME`, `SEND_RESULT`)
)Engine=InnoDB;

[INFO  20:39:34,736] <http-nio-80-exec-13> setup.UpgradeDatabase#upgrade:55 - Upgrade SQL(#25) >
alter table `robot_trigger_config`
  add column `WHEN_TIMER` varchar(100) comment '定期执行';

[INFO  20:39:34,939] <http-nio-80-exec-13> privileges.UserStore#init:517 - Loaded [ 3 ] users.
[INFO  20:39:35,017] <http-nio-80-exec-13> privileges.UserStore#init:525 - Loaded [ 2 ] roles.
[INFO  20:39:35,048] <http-nio-80-exec-13> privileges.UserStore#init:550 - Loaded [ 2 ] departments.
[INFO  20:39:35,064] <http-nio-80-exec-13> privileges.UserStore#init:558 - Loaded [ 1 ] teams.
[INFO  20:39:35,470] <http-nio-80-exec-13> setup.UpgradeDatabase#upgrade:62 - Upgrade database version : 24
[ERROR 20:39:35,470] <http-nio-80-exec-13> setup.UpgradeDatabase#upgradeQuietly:76 - Upgrade database failed! Already upgraded?
cn.devezhao.persist4j.DataAccessException: Batch SQL Error! #
        at com.rebuild.server.service.SQLExecutor.executeBatchInternal(SQLExecutor.java:127)
        at com.rebuild.server.service.SQLExecutor.executeBatch(SQLExecutor.java:106)
        at com.rebuild.server.helper.setup.UpgradeDatabase.upgrade(UpgradeDatabase.java:56)
        at com.rebuild.server.helper.setup.UpgradeDatabase.upgradeQuietly(UpgradeDatabase.java:74)
        at com.rebuild.server.Application.init(Application.java:140)
        at com.rebuild.server.ServerListener.contextInitialized(ServerListener.java:69)
        at com.rebuild.server.helper.setup.Installer.install(Installer.java:103)
        at com.rebuild.web.setup.InstallControll.installExec(InstallControll.java:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'WHEN_TIMER'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2067)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5175)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2052)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3253)
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1092)
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:491)
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3251)
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:194)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
        at cn.devezhao.persist4j.engine.JdbcSupport.execute(JdbcSupport.java:55)
        at cn.devezhao.persist4j.engine.JdbcSupport.executeBatch(JdbcSupport.java:69)
        at com.rebuild.server.service.SQLExecutor.executeBatchInternal(SQLExecutor.java:122)
        ... 50 more

### 如何复现此问题
新安装 rebuild-standalone-1.10.0

### 系统环境（操作系统/MySQL版本/浏览器）
Windows Server 2019 amd64
MySQL 5.7.29
Chrome 83.0.4103.106（正式版本） （64 位）

**Comment by devezhao** [comment]
此为升级新版时更新数据库脚本报错。本地是否升级过开发版（develop 分支）？如果升级过那么可能出现冲突。

**Comment by aertaa** [comment]
并未升级过开发版，使用了 rebuild-standalone-1.10.0.zip ，重新安装时删除了 .rebuild 文件夹，删除了原数据库并执行以下内容：
CREATE DATABASE rebuild10 COLLATE utf8mb4_general_ci;
#CREATE USER 'rebuild'@'127.0.0.1' IDENTIFIED BY 'rebuild';
GRANT ALL PRIVILEGES ON rebuild10.* TO 'rebuild'@'127.0.0.1';
FLUSH PRIVILEGES;

**Comment by devezhao** [comment]
本地缓存（ehcache/redis）所致，已发布修订版 v1.10.1 https://github.com/getrebuild/rebuild/releases/tag/1.10.1
