### ISSUE TITLE
导入实体出错

### ISSUE THREAD

**Issue by UsernameFull** [getrebuild/rebuild#207]
### 版本
1.10.3

### 什么问题 
导入实体出错。
错误日志
[ERROR 14:30:41,191] <http-nio-8080-exec-29> web.RebuildExceptionResolver#resolveException:42 - 
Handler   : public void com.rebuild.web.admin.rbstore.MetaschemaControll.imports(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException
Exception : 
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at com.rebuild.web.admin.rbstore.MetaschemaControll.imports(MetaschemaControll.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 32 more
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:261)
	at com.rebuild.server.helper.task.TaskExecutors.<clinit>(TaskExecutors.java:44)
	... 44 more

### 如何复现此问题
配置好环境后只要选择从RB仓库导入实体就会报错

### 系统环境（操作系统/MySQL版本/浏览器）
centos7
mysql5.6
java8

**Comment by bingyuxq** [comment]
看起来是没获取到文件，应该只是简单的服务器文件不存在

**Comment by devezhao** [comment]
可以在服务器上访问此文件试试 https://getrebuild.com/gh/getrebuild/rebuild-datas/metaschemas/SALESORDER-1.0.json

**Comment by UsernameFull** [comment]
> 可以在服务器上访问此文件试试 https://getrebuild.com/gh/getrebuild/rebuild-datas/metaschemas/SALESORDER-1.0.json

同时也有一个类似的问题，就是上传excel也会出错，应该都是网络方面的问题。服务器上直接wget访问文件没问题

**Comment by UsernameFull** [comment]
> 可以在服务器上访问此文件试试 https://getrebuild.com/gh/getrebuild/rebuild-datas/metaschemas/SALESORDER-1.0.json

同时也有一个类似的问题，就是上传excel也会出错，应该都是网络方面的问题。服务器上直接wget访问文件没问题

**Comment by devezhao** [comment]
启动 RB 使用的是哪个用户？是否有写权限的问题？
可以把完整的日志文件发出来，上面贴的堆栈不是很全面。（日志文件位于 `$TOMCAT$/temp/logs/`）

**Comment by UsernameFull** [comment]
> 启动 RB 使用的是哪个用户？是否有写权限的问题？
> 可以把完整的日志文件发出来，上面贴的堆栈不是很全面。（日志文件位于 `$TOMCAT$/temp/logs/`）

13-Aug-2020 14:48:05.995 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.40
13-Aug-2020 14:48:05.996 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Apr 10 2019 14:31:19 UTC
13-Aug-2020 14:48:05.996 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.40.0
13-Aug-2020 14:48:05.996 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-1127.13.1.el7.x86_64
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/jdk1.8.0_121/jre
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_121-b13
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/rebuild-standalone
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/rebuild-standalone
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/rebuild-standalone/conf/logging.properties
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
13-Aug-2020 14:48:05.997 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/rebuild-standalone
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/rebuild-standalone
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/rebuild-standalone/temp
13-Aug-2020 14:48:05.998 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
13-Aug-2020 14:48:06.248 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-18080"]
13-Aug-2020 14:48:06.278 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
13-Aug-2020 14:48:06.309 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 995 ms
13-Aug-2020 14:48:06.325 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
13-Aug-2020 14:48:06.325 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.40
13-Aug-2020 14:48:11.160 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[INFO  14:48:11,306] <localhost-startStop-1> server.ServerListener#contextInitialized:52 - Rebuild Booting (1.10.3) ...
[WARN  14:48:11,480] <localhost-startStop-1> server.ServerListener#contextInitialized:63 - 
###################################################################

  REBUILD IS WAITING FOR INSTALL ...
  
  Install URL : http://localhost:18080/
  
  Version : 1.10.3
  OS      : Linux amd64
  Report an issue :
  https://getrebuild.com/report-issue?title=boot

###################################################################
13-Aug-2020 14:48:14.062 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-18080"]
13-Aug-2020 14:48:14.154 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 7844 ms
[INFO  14:48:16,038] <http-nio-18080-exec-7> language.Languages#reset:61 - Loading language bundle : ja
[INFO  14:48:16,106] <http-nio-18080-exec-7> language.Languages#reset:61 - Loading language bundle : en
[INFO  14:48:16,109] <http-nio-18080-exec-7> language.Languages#reset:61 - Loading language bundle : zh-CN
[INFO  14:49:40,175] <http-nio-18080-exec-14> setup.Installer#installDatabase:212 - Schemes of database created : 43
[WARN  14:49:40,357] <http-nio-18080-exec-14> setup.Installer#install:94 - Stored install file : /root/.rebuild/.rebuild
[INFO  14:49:40,358] <http-nio-18080-exec-14> server.ServerListener#contextInitialized:52 - Rebuild Booting (1.10.3) ...
[INFO  14:49:40,358] <http-nio-18080-exec-14> server.ServerListener#contextInitialized:67 - Initializing Spring context ...
13-Aug-2020 14:49:40.804 WARNING [http-nio-18080-exec-14] java.util.prefs.FileSystemPreferences$6.run Prefs file removed in background /root/.java/.userPrefs/prefs.xml
13-Aug-2020 14:49:40.804 WARNING [http-nio-18080-exec-14] java.util.prefs.FileSystemPreferences$6.run Prefs file removed in background /usr/local/jdk1.8.0_121/jre/.systemPrefs/prefs.xml
[INFO  14:49:41,783] <http-nio-18080-exec-14> server.ServerStatus$Status#<init>:183 - Checking Create File : [ OK ]
[INFO  14:49:41,907] <http-nio-18080-exec-14> server.ServerStatus$Status#<init>:183 - Checking Database : [ OK ]
[WARN  14:49:42,400] <http-nio-18080-exec-14> cache.BaseCacheTemplate#testJedisPool:133 - Acquisition J/Redis failed : Connection refused (Connection refused) !!! Using backup ehcache for class com.rebuild.server.helper.cache.CommonCache
[INFO  14:49:42,410] <http-nio-18080-exec-14> server.ServerStatus$Status#<init>:183 - Checking Cache/EHCACHE : [ OK ]
[INFO  14:49:44,255] <http-nio-18080-exec-14> server.Application#init:148 - Loading customized/business entities ...
[INFO  14:49:45,181] <http-nio-18080-exec-14> base.GeneralEntityService#<init>:90 - com.rebuild.server.service.base.GeneralEntityService@108ee085 add observer : com.rebuild.server.service.notification.NotificationObserver@7e0de520
[INFO  14:49:45,181] <http-nio-18080-exec-14> base.GeneralEntityService#<init>:90 - com.rebuild.server.service.base.GeneralEntityService@108ee085 add observer : com.rebuild.server.service.base.RevisionHistoryObserver@22bacc9b
[INFO  14:49:45,182] <http-nio-18080-exec-14> base.GeneralEntityService#<init>:90 - com.rebuild.server.service.base.GeneralEntityService@108ee085 add observer : com.rebuild.server.service.base.AttachmentAwareObserver@470feb4f
[INFO  14:49:45,182] <http-nio-18080-exec-14> base.GeneralEntityService#<init>:90 - com.rebuild.server.service.base.GeneralEntityService@108ee085 add observer : com.rebuild.server.business.trigger.RobotTriggerObserver@73c75819
[INFO  14:49:45,296] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.MetaEntity@4ae9014a
[INFO  14:49:45,302] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.MetaField@34517c1b
[INFO  14:49:45,308] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.PickList@164cf123
[INFO  14:49:45,341] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Classification@c8de97a
[INFO  14:49:45,348] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.AutoFillinConfig@3c788bd1
[INFO  14:49:45,375] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.RobotTriggerConfig@3cd86b6a
[INFO  14:49:45,383] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.RobotApprovalConfig@4db9dbd
[INFO  14:49:45,417] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.FilterConfig@255914d6
[INFO  14:49:45,422] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.LayoutConfig@49738ff5
[INFO  14:49:45,432] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.DashboardConfig@6a64366c
[INFO  14:49:45,437] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.ChartConfig@36b4d210
[INFO  14:49:45,444] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.RebuildApi@663aba2c
[INFO  14:49:45,453] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.DataReportConfig@2ccde3d0
[INFO  14:49:45,490] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.RobotApprovalStep@364f5fce
[INFO  14:49:45,495] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.AttachmentFolder@6062fcf4
[INFO  14:49:45,502] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.User@793abfc8
[INFO  14:49:45,507] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Department@3273c52e
[INFO  14:49:45,513] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Role@69fc08b9
[INFO  14:49:45,550] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Team@7428ce8a
[INFO  14:49:45,554] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Notification@12cfef7
[INFO  14:49:45,560] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.Feeds@41ab51be
[INFO  14:49:45,572] <http-nio-18080-exec-14> server.Application#init:157 - Service specification : service.FeedsComment@69ac9f98
[INFO  14:49:45,662] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : entity/update : com.rebuild.api.general.EntityUpdate
[INFO  14:49:45,662] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : entity/delete : com.rebuild.api.general.EntityDelete
[INFO  14:49:45,663] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : entity/get : com.rebuild.api.general.EntityGet
[INFO  14:49:45,663] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : entity/create : com.rebuild.api.general.EntityCreate
[INFO  14:49:45,663] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : entity/list : com.rebuild.api.general.EntityList
[INFO  14:49:45,664] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : metadata/fields : com.rebuild.api.metadata.FieldList
[INFO  14:49:45,664] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : metadata/classification-data : com.rebuild.api.metadata.ClassificationData
[INFO  14:49:45,664] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : metadata/entities : com.rebuild.api.metadata.EntityList
[INFO  14:49:45,664] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : system-time : com.rebuild.api.SystemTime
[INFO  14:49:45,665] <http-nio-18080-exec-14> api.ApiGateway#registerApi:253 - New API registered : login-token : com.rebuild.api.LoginToken
[INFO  14:49:45,665] <http-nio-18080-exec-14> server.Application#init:174 - Rebuild Boot successful in 5307 ms
[INFO  14:49:46,430] <http-nio-18080-exec-14> privileges.UserStore#init:518 - Loaded [ 3 ] users.
[INFO  14:49:46,466] <http-nio-18080-exec-14> privileges.UserStore#init:526 - Loaded [ 2 ] roles.
[INFO  14:49:46,488] <http-nio-18080-exec-14> privileges.UserStore#init:551 - Loaded [ 2 ] departments.
[INFO  14:49:46,498] <http-nio-18080-exec-14> privileges.UserStore#init:559 - Loaded [ 1 ] teams.
[INFO  14:49:46,693] <http-nio-18080-exec-14> server.Application#init:176 - REBUILD AUTHORITY : GitHub | 无 | RBZ10UN-279JL1K44KBPPD7J | 开源社区版
[WARN  14:49:46,724] <http-nio-18080-exec-14> web.RequestWatchHandler#logProgressTime:142 - Method handle time 7777 ms. Request URL [ /setup/install-rebuild ] from [ http://121.196.183.134:18080/setup/install ]
[WARN  14:49:54,202] <http-nio-18080-exec-20> cache.BaseCacheTemplate#testJedisPool:133 - Acquisition J/Redis failed : Connection refused (Connection refused) !!! Using backup ehcache for class com.rebuild.server.helper.cache.RecordOwningCache
[WARN  14:49:55,102] <http-nio-18080-exec-21> web.RequestWatchHandler#logProgressTime:142 - Method handle time 724 ms. Request URL [ /dashboard/home ] from [ http://121.196.183.134:18080/user/login ]
[WARN  14:49:55,437] <http-nio-18080-exec-24> helper.QiniuCloud#<init>:59 - No QiniuCloud configuration! Using local storage.
[WARN  14:50:01,703] <http-nio-18080-exec-5> web.RequestWatchHandler#logProgressTime:142 - Method handle time 597 ms. Request URL [ /admin/systems ] from [ http://121.196.183.134:18080/user/admin-entry?nexturl=%2Fadmin%2Fsystems ]
[ERROR 14:50:08,941] <http-nio-18080-exec-27> web.RebuildExceptionResolver#resolveException:42 - 
Handler   : public void com.rebuild.web.admin.rbstore.MetaschemaControll.imports(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException
Exception : 
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at com.rebuild.web.admin.rbstore.MetaschemaControll.imports(MetaschemaControll.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 32 more
Caused by: java.lang.IllegalArgumentException
	at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:261)
	at com.rebuild.server.helper.task.TaskExecutors.<clinit>(TaskExecutors.java:44)
	... 44 more
[ERROR 14:50:08,944] <http-nio-18080-exec-27> web.RequestWatchHandler#afterCompletion:124 - 
++ EXECUTE REQUEST ERROR(s) TRACE +++++++++++++++++++++++++++++++++++++++++++++
User      : 001-0000000000000001
Handler   : /admin/metaschema/imports [ public void com.rebuild.web.admin.rbstore.MetaschemaControll.imports(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException ]
IP        : 122.188.163.158
Referer   : http://121.196.183.134:18080/admin/p/entityhub/entity-new
UserAgent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
Cause     : java.lang.IllegalArgumentException
Message   : -
java.lang.IllegalArgumentException
	at java.util.concurrent.LinkedBlockingQueue.<init>(LinkedBlockingQueue.java:261)
	at com.rebuild.server.helper.task.TaskExecutors.<clinit>(TaskExecutors.java:44)
	at com.rebuild.web.admin.rbstore.MetaschemaControll.imports(MetaschemaControll.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by devezhao** [comment]
已经修复了，会在 V1.11 中发布（预计1-2周内）。原因是任务执行数未考虑单核 CPU 的情况，https://github.com/getrebuild/rebuild/blob/99cecf4795b89b9919a0454a5cff4a008239cb5b/src/main/java/com/rebuild/server/helper/task/TaskExecutors.java#L40

**Comment by UsernameFull** [comment]
> 已经修复了，会在 V1.11 中发布（预计1-2周内）。原因是任务执行数未考虑单核 CPU 的情况，
> 
> https://github.com/getrebuild/rebuild/blob/99cecf4795b89b9919a0454a5cff4a008239cb5b/src/main/java/com/rebuild/server/helper/task/TaskExecutors.java#L40

难怪我换了系统都解决不了。。。。原来是服务器不行
